services:
  frontend:
    build: ./frontend-service
    container_name: bazar_frontend
    ports:
      - "3000:3000"
    depends_on:
      - catalog
      - order

  catalog:
    build: ./catalog-service
    container_name: bazar_catalog
    ports:
      - "3001:3001"
    volumes:
      - ./catalog-service/data:/app/data

  order:
    build: ./order-service
    container_name: bazar_order
    ports:
      - "3002:3002"
    volumes:
      - ./order-service/data:/app/data
    depends_on:
      - catalog