services:
  frontend:
    build: ./frontend-service
    container_name: bazar_frontend
    ports:
      - "3000:3000"
    depends_on:
      - catalog1
      - catalog2
      - order1
      - order2

  catalog1:
    build: ./catalog-service
    container_name: bazar_catalog1
    ports:
      - "3001:3001"
    environment:
      - CATALOG_FILE=catalog1.csv
      - REPLICA_SYNC_URL=http://catalog2:3001
    volumes:
      - ./catalog-service/data/catalog1.csv:/app/data/catalog1.csv:Z

  catalog2:
    build: ./catalog-service
    container_name: bazar_catalog2
    ports:
      - "3003:3001"
    environment:
      - CATALOG_FILE=catalog2.csv
      - REPLICA_SYNC_URL=http://catalog1:3001
    volumes:
      - ./catalog-service/data/catalog2.csv:/app/data/catalog2.csv:Z

  order1:
    build: ./order-service
    container_name: bazar_order1
    ports:
      - "3002:3002"
    environment:
      - ORDERS_FILE=orders1.csv
      - CATALOG_SERVICE_URL=http://catalog1:3001
      - FRONTEND_SERVICE_URL=http://frontend:3000
      - ORDER_SYNC_URL=http://order2:3002
    volumes:
      - ./order-service/data/orders1.csv:/app/data/orders1.csv:Z
    depends_on:
      - catalog1
      - catalog2

  order2:
    build: ./order-service
    container_name: bazar_order2
    ports:
      - "3004:3002"
    environment:
      - ORDERS_FILE=orders2.csv
      - CATALOG_SERVICE_URL=http://catalog2:3001
      - FRONTEND_SERVICE_URL=http://frontend:3000
      - ORDER_SYNC_URL=http://order1:3002
    volumes:
      - ./order-service/data/orders2.csv:/app/data/orders2.csv:Z
    depends_on:
      - catalog1
      - catalog2